language: python
sudo: false
cache:
  pip: true
  directories:
    - eggs
    - downloads
python:
  - 2.7
env:
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1
  - PLONE_VERSION=5.2
allow_failures:
  - env: PLONE_VERSION=5.2
matrix:
  fast_finish: true
install:
  - virtualenv .
  - bin/pip install -r requirements.txt
  - bin/pip install selenium
  - ls -la ./selenium
  - export PATH=$PWD/selenium:$PATH
  - pwd
  - echo $PATH
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v
script:
  - bin/code-analysis
  - bin/test --all
after_success:
  - bin/createcoverage
  - pip install coveralls
  - bin/python -m coverage.pickle2json
  - pip install coveralls
  - coveralls
notifications:
  email:
    - k.suess@rohberg.ch
