language: python
sudo: false
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=5.1.x
    - python: "2.7"
      env: PLONE_VERSION=5.2.x
    - python: "3.6"
      env: PLONE_VERSION=5.2.x
      dist: bionic
    - python: "3.7"
      env: PLONE_VERSION=5.2.x
      dist: bionic
      sudo: true
  fast_finish: true
cache:
  pip: true
  directories:
# - $HOME/buildout-cache
before_install:
# install chrome webdriver
  - mkdir webdriver;
    wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz;
    tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C webdriver;
    wget https://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip;
    unzip chromedriver_linux64.zip -d webdriver;
    export PATH=$PATH:$(pwd)/webdriver;
  - cp plone-$PLONE_VERSION.cfg buildout.cfg
install:
  - virtualenv .
  - python --version
  - bin/pip install -r requirements.txt
  - bin/buildout -N annotate
  - bin/buildout -N
before_script:
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3
script:
  - bin/test
  - bin/test -t *.robot --all
after_success:
  - bin/code-analysis
  - bin/createcoverage
  - bin/pip install coverage
  - bin/python -m coverage.pickle2json
  - pip install coveralls
  - coveralls
notifications:
  email:
    - k.suess@rohberg.ch
